server:
  port: 8090

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50  # 한 번에 50개씩 배치로 저장
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: 133.186.217.162
      port: 25015
      username: globepoint
      authentication-database: admin
      password: globep0int
      database: vrware_member
